import { PlaylistItem } from "@nomercy-entertainment/nomercy-video-player/src/types";

const playlist: PlaylistItem[] = [
	{
		id: 'sintel',
		title: 'Sintel',
		description: 'Sintel is an independently produced short film, initiated by the Blender Foundation as a means to further improve and validate the free/open source 3D creation suite Blender. With initial funding provided by 1000s of donations via the internet community, it has again proven to be a viable development model for both open 3D technology as for independent animation film.\nThis 15 minute film has been realized in the studio of the Amsterdam Blender Institute, by an international team of artists and developers. In addition to that, several crucial technical and creative targets have been realized online, by developers and artists and teams all over the world.\nwww.sintel.org',
		image: '/q2bVM5z90tCGbmXYtq2J38T5hSX.jpg',
		file: '/Sintel.(2010)/Sintel.(2010).NoMercy.m3u8',
		duration: '14:48',
		// season: 1,
		episode: 1,
		year: 2010,
		tracks: [
			{
				id: 0,
				label: 'Dutch (Full)',
				file: '/Sintel.(2010)/subtitles/Sintel.(2010).NoMercy.dut.full.vtt',
				language: 'dut',
				kind: 'subtitles',
			},
			{
				id: 1,
				label: 'English (Full)',
				type: 'sdh',
				file: '/Sintel.(2010)/subtitles/Sintel.(2010).NoMercy.eng.full.vtt',
				language: 'eng',
				kind: 'subtitles',
			},
			{
				id: 2,
				label: 'French (Full)',
				file: '/Sintel.(2010)/subtitles/Sintel.(2010).NoMercy.fre.full.vtt',
				language: 'fre',
				kind: 'subtitles',
			},
			{
				id: 3,
				label: 'German (Full)',
				type: 'sdh',
				file: '/Sintel.(2010)/subtitles/Sintel.(2010).NoMercy.ger.full.vtt',
				language: 'ger',
				kind: 'subtitles',
			},
			{
				id: 4,
				label: 'Italian (Full)',
				file: '/Sintel.(2010)/subtitles/Sintel.(2010).NoMercy.ita.full.vtt',
				language: 'ita',
				kind: 'subtitles',
			},
			{
				id: 5,
				label: 'Russian (Full)',
				file: '/Sintel.(2010)/subtitles/Sintel.(2010).NoMercy.rus.full.vtt',
				language: 'rus',
				kind: 'subtitles',
			},
			{
				id: 6,
				label: 'German (Full)',
				file: '/Sintel.(2010)/subtitles/Sintel.(2010).NoMercy.ger.full.vtt',
				language: 'ger',
				kind: 'subtitles',
			},
			{
				id: 7,
				label: 'Portuguese (Full)',
				file: '/Sintel.(2010)/subtitles/Sintel.(2010).NoMercy.por.full.vtt',
				language: 'por',
				kind: 'subtitles',
			},
			{
				id: 8,
				label: 'Spanish (Full)',
				file: '/Sintel.(2010)/subtitles/Sintel.(2010).NoMercy.spa.full.vtt',
				language: 'spa',
				kind: 'subtitles',
			},
			{
				id: 9,
				label: 'Polish (Full)',
				file: '/Sintel.(2010)/subtitles/Sintel.(2010).NoMercy.pol.full.vtt',
				language: 'pol',
				kind: 'subtitles',
			},
			{
				id: 10,
				file: '/Sintel.(2010)/thumbs_256x109.vtt',
				kind: 'thumbnails',
			},
			{
				id: 11,
				file: '/Sintel.(2010)/chapters.vtt',
				kind: 'chapters',
			},
			{
				id: 12,
				file: '/Sintel.(2010)/thumbs_256x109.webp',
				kind: 'sprite',
			},
		],
	},
	// Cosmos Laundromat is held from publish pending a re-encode (HEVC + LUT
	// + font extraction were misclassified in the original pass). The files
	// are not on nomercy-media yet; restore this entry once the re-encode
	// lands and the asset paths are populated. See journal entry on the
	// encoder LUT misclassification fix for context.
	{
		id: 'big-buck-bunny',
		title: 'Big Buck Bunny',
		description: 'Big Buck Bunny tells the story of a giant rabbit with a heart bigger than himself. When one sunny day three rodents rudely harass him, something snaps... and the rabbit ain\'t no bunny anymore! In the typical cartoon tradition he prepares the nasty rodents a comical revenge.',
		image: '/xtdybjRRZ15mCrPOvEld305myys.jpg',
		file: '/Big.Buck.Bunny.(2008)/Big.Buck.Bunny.(2008).NoMercy.m3u8',
		duration: '9:56',
		episode: 3,
		year: 2015,
		tracks: [
			{
				id: 0,
				file: '/Big.Buck.Bunny.(2008)/thumbs_320x178.vtt',
				kind: 'thumbnails',
			},
			{
				id: 1,
				file: '/Big.Buck.Bunny.(2008)/chapters.vtt',
				kind: 'chapters',
			},
			{
				id: 2,
				file: '/Big.Buck.Bunny.(2008)/thumbs_320x178.webp',
				kind: 'sprite',
			},
		],
	},
	{
		id: 'tears-of-steel',
		title: 'Tears of Steel',
		description: 'Tears of Steel was realized with crowd-funding by users of the open source 3D creation tool Blender. Target was to improve and test a complete open and free pipeline for visual effects in film - and to make a compelling sci-fi film in Amsterdam, the Netherlands.  The film itself, and all raw material used for making it, have been released under the Creatieve Commons 3.0 Attribution license. Visit the tearsofsteel.org website to find out more about this, or to purchase the 4-DVD box with a lot of extras.  (CC) Blender Foundation - https://www.tearsofsteel.org',
		image: '/fOy6SL5Zs2PFcNXwqEPIDPrLB1q.jpg',
		file: '/Tears.of.Steel.(2012)/Tears.of.Steel.(2012).NoMercy.m3u8',
		duration: '12:13',
		episode: 4,
		year: 2012,
		tracks: [
			{
				id: 0,
				label: 'Brazilian (Full)',
				type: 'sdh',
				file: '/Tears.of.Steel.(2012)/subtitles/Tears.of.Steel.(2012).NoMercy.bra.full.vtt',
				language: 'bra',
				kind: 'subtitles',
			},
			{
				id: 1,
				label: 'Chinese (Full)',
				type: 'sdh',
				file: '/Tears.of.Steel.(2012)/subtitles/Tears.of.Steel.(2012).NoMercy.chi.full.vtt',
				language: 'chi',
				kind: 'subtitles',
			},
			{
				id: 2,
				label: 'Croatian (Full)',
				type: 'sdh',
				file: '/Tears.of.Steel.(2012)/subtitles/Tears.of.Steel.(2012).NoMercy.cro.full.vtt',
				language: 'cro',
				kind: 'subtitles',
			},
			{
				id: 3,
				label: 'Chech (Full)',
				type: 'sdh',
				file: '/Tears.of.Steel.(2012)/subtitles/Tears.of.Steel.(2012).NoMercy.cze.full.vtt',
				language: 'cze',
				kind: 'subtitles',
			},
			{
				id: 4,
				label: 'Danish (Full)',
				type: 'sdh',
				file: '/Tears.of.Steel.(2012)/subtitles/Tears.of.Steel.(2012).NoMercy.dan.full.vtt',
				language: 'dan',
				kind: 'subtitles',
			},
			{
				id: 5,
				label: 'Dutch (Full)',
				type: 'sdh',
				file: '/Tears.of.Steel.(2012)/subtitles/Tears.of.Steel.(2012).NoMercy.dut.full.vtt',
				language: 'dut',
				kind: 'subtitles',
			},
			{
				id: 6,
				label: 'English (Full)',
				type: 'sdh',
				file: '/Tears.of.Steel.(2012)/subtitles/Tears.of.Steel.(2012).NoMercy.eng.full.vtt',
				language: 'eng',
				kind: 'subtitles',
			},
			{
				id: 7,
				label: 'French (Full)',
				type: 'sdh',
				file: '/Tears.of.Steel.(2012)/subtitles/Tears.of.Steel.(2012).NoMercy.fre.full.vtt',
				language: 'fre',
				kind: 'subtitles',
			},
			{
				id: 8,
				label: 'German (Full)',
				type: 'sdh',
				file: '/Tears.of.Steel.(2012)/subtitles/Tears.of.Steel.(2012).NoMercy.ger.full.vtt',
				language: 'ger',
				kind: 'subtitles',
			},
			{
				id: 9,
				label: 'Greek (Full)',
				type: 'sdh',
				file: '/Tears.of.Steel.(2012)/subtitles/Tears.of.Steel.(2012).NoMercy.gre.full.vtt',
				language: 'gre',
				kind: 'subtitles',
			},
			{
				id: 10,
				label: 'Hebrew (Full)',
				type: 'sdh',
				file: '/Tears.of.Steel.(2012)/subtitles/Tears.of.Steel.(2012).NoMercy.heb.full.vtt',
				language: 'heb',
				kind: 'subtitles',
			},
			{
				id: 11,
				label: 'Hungarian (Full)',
				type: 'sdh',
				file: '/Tears.of.Steel.(2012)/subtitles/Tears.of.Steel.(2012).NoMercy.hun.full.vtt',
				language: 'hun',
				kind: 'subtitles',
			},
			{
				id: 12,
				label: 'Indian (Full)',
				type: 'sdh',
				file: '/Tears.of.Steel.(2012)/subtitles/Tears.of.Steel.(2012).NoMercy.ind.full.vtt',
				language: 'ind',
				kind: 'subtitles',
			},
			{
				id: 13,
				label: 'Italian (Full)',
				type: 'sdh',
				file: '/Tears.of.Steel.(2012)/subtitles/Tears.of.Steel.(2012).NoMercy.ita.full.vtt',
				language: 'ita',
				kind: 'subtitles',
			},
			{
				id: 14,
				label: 'Japanese (Full)',
				type: 'sdh',
				file: '/Tears.of.Steel.(2012)/subtitles/Tears.of.Steel.(2012).NoMercy.jpn.full.vtt',
				language: 'jpn',
				kind: 'subtitles',
			},
			{
				id: 15,
				label: 'Norwegian (Full)',
				type: 'sdh',
				file: '/Tears.of.Steel.(2012)/subtitles/Tears.of.Steel.(2012).NoMercy.nor.full.vtt',
				language: 'nor',
				kind: 'subtitles',
			},
			{
				id: 16,
				label: 'Persian (Full)',
				type: 'sdh',
				file: '/Tears.of.Steel.(2012)/subtitles/Tears.of.Steel.(2012).NoMercy.per.full.vtt',
				language: 'per',
				kind: 'subtitles',
			},
			{
				id: 17,
				label: 'Portugese (Full)',
				type: 'sdh',
				file: '/Tears.of.Steel.(2012)/subtitles/Tears.of.Steel.(2012).NoMercy.por.full.vtt',
				language: 'por',
				kind: 'subtitles',
			},
			{
				id: 18,
				label: 'Russian (Full)',
				type: 'sdh',
				file: '/Tears.of.Steel.(2012)/subtitles/Tears.of.Steel.(2012).NoMercy.rus.full.vtt',
				language: 'rus',
				kind: 'subtitles',
			},
			{
				id: 19,
				label: 'Spanish (Full)',
				type: 'sdh',
				file: '/Tears.of.Steel.(2012)/subtitles/Tears.of.Steel.(2012).NoMercy.spa.full.vtt',
				language: 'spa',
				kind: 'subtitles',
			},
			{
				id: 20,
				file: '/Tears.of.Steel.(2012)/previews.vtt',
				kind: 'thumbnails',
			},
			{
				id: 21,
				file: '/Tears.of.Steel.(2012)/chapters.vtt',
				kind: 'chapters',
			},
			{
				id: 22,
				file: '/Tears.of.Steel.(2012)/sprite.webp',
				kind: 'sprite',
			},
		],
	},
	{
		id: 'elephants-dream',
		title: 'Elephants Dream',
		year: 2006,
		duration: '10:54',
		description: 'Two strange characters explore a capricious and seemingly infinite machine.',
		file: '/Elephants.Dream.(2006)/Elephants.Dream.(2006).NoMercy.m3u8',
		episode: 5,
		image: '/9bJDwuhza19HQcYA99FeslLYmUm.jpg',
		tracks: [
			{
				id: 0,
				label: 'Arabic',
				language: 'ara',
				kind: 'subtitles',
				file: '/Elephants.Dream.(2006)/subtitles/Elephants.Dream.(2006).NoMercy.ara.full.vtt',
			},
			{
				id: 1,
				label: 'Dutch',
				language: 'dut',
				kind: 'subtitles',
				file: '/Elephants.Dream.(2006)/subtitles/Elephants.Dream.(2006).NoMercy.dut.full.vtt',
			},
			{
				id: 2,
				label: 'English',
				language: 'eng',
				kind: 'subtitles',
				file: '/Elephants.Dream.(2006)/subtitles/Elephants.Dream.(2006).NoMercy.eng.full.vtt',
			},
			{
				id: 3,
				label: 'Japanese',
				language: 'jpn',
				kind: 'subtitles',
				file: '/Elephants.Dream.(2006)/subtitles/Elephants.Dream.(2006).NoMercy.jpn.full.vtt',
			},
			{
				id: 4,
				label: 'Russian',
				language: 'rus',
				kind: 'subtitles',
				file: '/Elephants.Dream.(2006)/subtitles/Elephants.Dream.(2006).NoMercy.rus.full.vtt',
			},
			{
				id: 5,
				label: 'Swedish',
				language: 'swe',
				kind: 'subtitles',
				file: '/Elephants.Dream.(2006)/subtitles/Elephants.Dream.(2006).NoMercy.swe.full.vtt',
			},
			{
				id: 6,
				file: '/Elephants.Dream.(2006)/thumbs_320x178.vtt',
				kind: 'thumbnails',
			},
			{
				id: 7,
				file: '/Elephants.Dream.(2006)/thumbs_320x178.webp',
				kind: 'sprite',
			},
			{
				id: 8,
				kind: 'chapters',
				file: '/Elephants.Dream.(2006)/chapters.vtt',
			},
		],
	},
	{
		id: 'agent-327',
		title: 'Agent 327: Operation Barbershop',
		description: 'Agent 327 is investigating a clue that leads him to a shady barbershop in Amsterdam. Little does he know that he is being tailed by mercenary Boris Kloris.',
		image: '/aupI9kV5CawUp02XWnI2l7Ym9SH.jpg',
		file: '/Agent.327.Operation.Barbershop.(2017)/Agent.327.Operation.Barbershop.(2017).NoMercy.m3u8',
		duration: '3:51',
		episode: 6,
		year: 2017,
		tracks: [
			{
				id: 0,
				label: 'Dutch',
				language: 'dut',
				kind: 'subtitles',
				file: '/Agent.327.Operation.Barbershop.(2017)/subtitles/Agent.327.Operation.Barbershop.(2017).NoMercy.dut.full.vtt',
			},
			{
				id: 1,
				label: 'English',
				language: 'eng',
				kind: 'subtitles',
				file: '/Agent.327.Operation.Barbershop.(2017)/subtitles/Agent.327.Operation.Barbershop.(2017).NoMercy.eng.full.vtt',
			},
			{
				id: 2,
				file: '/Agent.327.Operation.Barbershop.(2017)/thumbs_320x132.vtt',
				kind: 'thumbnails',
			},
			{
				id: 3,
				file: '/Agent.327.Operation.Barbershop.(2017)/thumbs_320x132.webp',
				kind: 'sprite',
			},
		],
	},
	{
		id: 'caminandes-gran-dillama',
		title: 'Caminandes: Gran Dillama',
		description: 'A young llama named Koro discovers that the grass is always greener on the other side of the fence.',
		image: '/206A3X9EH42kmdQMECq90SbjHCn.jpg',
		file: '/Caminandes.Gran.Dillama.(2013)/Caminandes.Gran.Dillama.(2013).NoMercy.m3u8',
		duration: '2:26',
		episode: 7,
		year: 2013,
		tracks: [
			{
				id: 0,
				file: '/Caminandes.Gran.Dillama.(2013)/thumbs_320x178.vtt',
				kind: 'thumbnails',
			},
			{
				id: 1,
				file: '/Caminandes.Gran.Dillama.(2013)/thumbs_320x178.webp',
				kind: 'sprite',
			},
		],
	},
	{
		id: 'caminandes-llama-drama',
		title: 'Caminandes: Llama Drama',
		description: 'Koro wants to get to the other side of the road. The first episode of the Caminandes series.',
		image: '/mjkoC8Vo7fSHuqrbVQdI6cNwKA2.jpg',
		file: '/Caminandes.Llama.Drama.(2013)/Caminandes.Llama.Drama.(2013).NoMercy.m3u8',
		duration: '1:29',
		episode: 8,
		year: 2013,
		tracks: [
			{
				id: 0,
				file: '/Caminandes.Llama.Drama.(2013)/thumbs_320x178.vtt',
				kind: 'thumbnails',
			},
			{
				id: 1,
				file: '/Caminandes.Llama.Drama.(2013)/thumbs_320x178.webp',
				kind: 'sprite',
			},
		],
	},
	{
		id: 'caminandes-llamigos',
		title: 'Caminandes: Llamigos',
		description: 'Koro meets Oti, a pesky baby Magellanic penguin, in an epic battle over tasty red berries during winter.',
		image: '/tIX2BIhkhoFq1iwtHYzTSbHbe82.jpg',
		file: '/Caminandes.Llamigos.(2016)/Caminandes.Llamigos.(2016).NoMercy.m3u8',
		duration: '2:30',
		episode: 9,
		year: 2016,
		tracks: [
			{
				id: 0,
				file: '/Caminandes.Llamigos.(2016)/thumbs_320x178.vtt',
				kind: 'thumbnails',
			},
			{
				id: 1,
				file: '/Caminandes.Llamigos.(2016)/thumbs_320x178.webp',
				kind: 'sprite',
			},
		],
	},
	{
		id: 'charge',
		title: 'Charge',
		description: 'An old destitute man breaks into a battery factory but soon finds himself confronted by a deadly security droid and no way out.',
		image: '/hwvuivrtKFA4tPkW81txs7oKJOx.jpg',
		file: '/Charge.(2022)/Charge.(2022).NoMercy.m3u8',
		duration: '4:23',
		episode: 10,
		year: 2022,
		tracks: [
			{
				id: 0,
				file: '/Charge.(2022)/thumbs_320x133.vtt',
				kind: 'thumbnails',
			},
			{
				id: 1,
				file: '/Charge.(2022)/thumbs_320x133.webp',
				kind: 'sprite',
			},
		],
	},
	{
		id: 'coffee-run',
		title: 'Coffee Run',
		description: 'Fueled by caffeine, a young woman runs through the bittersweet memories of her past relationship.',
		image: '/pUHJzzq6fUowt8NrfDL5JAfjbqR.jpg',
		file: '/Coffee.Run.(2020)/Coffee.Run.(2020).NoMercy.m3u8',
		duration: '3:05',
		episode: 11,
		year: 2020,
		tracks: [
			{
				id: 0,
				file: '/Coffee.Run.(2020)/thumbs_320x133.vtt',
				kind: 'thumbnails',
			},
			{
				id: 1,
				file: '/Coffee.Run.(2020)/thumbs_320x133.webp',
				kind: 'sprite',
			},
		],
	},
	{
		id: 'glass-half',
		title: 'Glass Half',
		description: 'Two amateur art critics meet in a gallery and argue passionately about the pieces they see displayed.',
		image: '/AlqiewYiIpnoR4yqeo17y1SBf6S.jpg',
		file: '/Glass.Half.(2015)/Glass.Half.(2015).NoMercy.m3u8',
		duration: '3:13',
		episode: 12,
		year: 2015,
		tracks: [
			{
				id: 0,
				label: 'Afrikaans',
				language: 'afr',
				kind: 'subtitles',
				file: '/Glass.Half.(2015)/subtitles/Glass.Half.(2015).NoMercy.afr.full.vtt',
			},
			{
				id: 1,
				label: 'Arabic',
				language: 'ara',
				kind: 'subtitles',
				file: '/Glass.Half.(2015)/subtitles/Glass.Half.(2015).NoMercy.ara.full.vtt',
			},
			{
				id: 2,
				label: 'Chinese',
				language: 'chi',
				kind: 'subtitles',
				file: '/Glass.Half.(2015)/subtitles/Glass.Half.(2015).NoMercy.chi.full.vtt',
			},
			{
				id: 3,
				label: 'Danish',
				language: 'dan',
				kind: 'subtitles',
				file: '/Glass.Half.(2015)/subtitles/Glass.Half.(2015).NoMercy.dan.full.vtt',
			},
			{
				id: 4,
				label: 'Dutch',
				language: 'dut',
				kind: 'subtitles',
				file: '/Glass.Half.(2015)/subtitles/Glass.Half.(2015).NoMercy.dut.full.vtt',
			},
			{
				id: 5,
				label: 'English',
				language: 'eng',
				kind: 'subtitles',
				file: '/Glass.Half.(2015)/subtitles/Glass.Half.(2015).NoMercy.eng.full.vtt',
			},
			{
				id: 6,
				label: 'French',
				language: 'fre',
				kind: 'subtitles',
				file: '/Glass.Half.(2015)/subtitles/Glass.Half.(2015).NoMercy.fre.full.vtt',
			},
			{
				id: 7,
				label: 'German',
				language: 'ger',
				kind: 'subtitles',
				file: '/Glass.Half.(2015)/subtitles/Glass.Half.(2015).NoMercy.ger.full.vtt',
			},
			{
				id: 8,
				label: 'Hindi',
				language: 'hin',
				kind: 'subtitles',
				file: '/Glass.Half.(2015)/subtitles/Glass.Half.(2015).NoMercy.hin.full.vtt',
			},
			{
				id: 9,
				label: 'Indonesian',
				language: 'ind',
				kind: 'subtitles',
				file: '/Glass.Half.(2015)/subtitles/Glass.Half.(2015).NoMercy.ind.full.vtt',
			},
			{
				id: 10,
				label: 'Japanese',
				language: 'jpn',
				kind: 'subtitles',
				file: '/Glass.Half.(2015)/subtitles/Glass.Half.(2015).NoMercy.jpn.full.vtt',
			},
			{
				id: 11,
				label: 'Lithuanian',
				language: 'lit',
				kind: 'subtitles',
				file: '/Glass.Half.(2015)/subtitles/Glass.Half.(2015).NoMercy.lit.full.vtt',
			},
			{
				id: 12,
				label: 'Norwegian',
				language: 'nob',
				kind: 'subtitles',
				file: '/Glass.Half.(2015)/subtitles/Glass.Half.(2015).NoMercy.nob.full.vtt',
			},
			{
				id: 13,
				label: 'Polish',
				language: 'pol',
				kind: 'subtitles',
				file: '/Glass.Half.(2015)/subtitles/Glass.Half.(2015).NoMercy.pol.full.vtt',
			},
			{
				id: 14,
				label: 'Portuguese',
				language: 'por',
				kind: 'subtitles',
				file: '/Glass.Half.(2015)/subtitles/Glass.Half.(2015).NoMercy.por.full.vtt',
			},
			{
				id: 15,
				label: 'Romanian',
				language: 'ron',
				kind: 'subtitles',
				file: '/Glass.Half.(2015)/subtitles/Glass.Half.(2015).NoMercy.ron.full.vtt',
			},
			{
				id: 16,
				label: 'Serbian',
				language: 'srp',
				kind: 'subtitles',
				file: '/Glass.Half.(2015)/subtitles/Glass.Half.(2015).NoMercy.srp.full.vtt',
			},
			{
				id: 17,
				label: 'Tamil',
				language: 'tam',
				kind: 'subtitles',
				file: '/Glass.Half.(2015)/subtitles/Glass.Half.(2015).NoMercy.tam.full.vtt',
			},
			{
				id: 18,
				label: 'Telugu',
				language: 'tel',
				kind: 'subtitles',
				file: '/Glass.Half.(2015)/subtitles/Glass.Half.(2015).NoMercy.tel.full.vtt',
			},
			{
				id: 19,
				label: 'Turkish',
				language: 'tur',
				kind: 'subtitles',
				file: '/Glass.Half.(2015)/subtitles/Glass.Half.(2015).NoMercy.tur.full.vtt',
			},
			{
				id: 20,
				label: 'Vietnamese',
				language: 'vie',
				kind: 'subtitles',
				file: '/Glass.Half.(2015)/subtitles/Glass.Half.(2015).NoMercy.vie.full.vtt',
			},
			{
				id: 21,
				file: '/Glass.Half.(2015)/thumbs_320x180.vtt',
				kind: 'thumbnails',
			},
			{
				id: 22,
				file: '/Glass.Half.(2015)/thumbs_320x180.webp',
				kind: 'sprite',
			},
		],
	},
	{
		id: 'hero',
		title: 'HERO',
		description: 'What does it mean to be a true hero? A short animation showcasing Blender\'s Grease Pencil tool for 2D animation within a full 3D pipeline.',
		image: '/7poXZZ6JZA0AN9nhXvt8JbzlX7T.jpg',
		file: '/HERO.(2018)/HERO.(2018).NoMercy.m3u8',
		duration: '3:57',
		episode: 13,
		year: 2018,
		tracks: [
			{
				id: 0,
				file: '/HERO.(2018)/thumbs_320x132.vtt',
				kind: 'thumbnails',
			},
			{
				id: 1,
				file: '/HERO.(2018)/thumbs_320x132.webp',
				kind: 'sprite',
			},
		],
	},
	{
		id: 'spring',
		title: 'Spring',
		description: 'The story of a shepherd girl and her dog, who face ancient spirits in order to continue the cycle of life.',
		image: '/lL04DVOu1b64Xoj1EuWHZdtcfaZ.jpg',
		file: '/Spring.(2019)/Spring.(2019).NoMercy.m3u8',
		duration: '7:44',
		episode: 14,
		year: 2019,
		tracks: [
			{
				id: 0,
				label: 'Arabic',
				language: 'ara',
				kind: 'subtitles',
				file: '/Spring.(2019)/subtitles/Spring.(2019).NoMercy.ara.full.vtt',
			},
			{
				id: 1,
				label: 'Dutch',
				language: 'dut',
				kind: 'subtitles',
				file: '/Spring.(2019)/subtitles/Spring.(2019).NoMercy.dut.full.vtt',
			},
			{
				id: 2,
				label: 'English',
				language: 'eng',
				kind: 'subtitles',
				file: '/Spring.(2019)/subtitles/Spring.(2019).NoMercy.eng.full.vtt',
			},
			{
				id: 3,
				label: 'Hindi',
				language: 'hin',
				kind: 'subtitles',
				file: '/Spring.(2019)/subtitles/Spring.(2019).NoMercy.hin.full.vtt',
			},
			{
				id: 4,
				label: 'Hungarian',
				language: 'hun',
				kind: 'subtitles',
				file: '/Spring.(2019)/subtitles/Spring.(2019).NoMercy.hun.full.vtt',
			},
			{
				id: 5,
				label: 'Indonesian',
				language: 'ind',
				kind: 'subtitles',
				file: '/Spring.(2019)/subtitles/Spring.(2019).NoMercy.ind.full.vtt',
			},
			{
				id: 6,
				label: 'Japanese',
				language: 'jpn',
				kind: 'subtitles',
				file: '/Spring.(2019)/subtitles/Spring.(2019).NoMercy.jpn.full.vtt',
			},
			{
				id: 7,
				label: 'Korean',
				language: 'kor',
				kind: 'subtitles',
				file: '/Spring.(2019)/subtitles/Spring.(2019).NoMercy.kor.full.vtt',
			},
			{
				id: 8,
				label: 'Lithuanian',
				language: 'lit',
				kind: 'subtitles',
				file: '/Spring.(2019)/subtitles/Spring.(2019).NoMercy.lit.full.vtt',
			},
			{
				id: 9,
				label: 'Polish',
				language: 'pol',
				kind: 'subtitles',
				file: '/Spring.(2019)/subtitles/Spring.(2019).NoMercy.pol.full.vtt',
			},
			{
				id: 10,
				label: 'Portuguese',
				language: 'por',
				kind: 'subtitles',
				file: '/Spring.(2019)/subtitles/Spring.(2019).NoMercy.por.full.vtt',
			},
			{
				id: 11,
				label: 'Spanish',
				language: 'spa',
				kind: 'subtitles',
				file: '/Spring.(2019)/subtitles/Spring.(2019).NoMercy.spa.full.vtt',
			},
			{
				id: 12,
				label: 'Serbian',
				language: 'srp',
				kind: 'subtitles',
				file: '/Spring.(2019)/subtitles/Spring.(2019).NoMercy.srp.full.vtt',
			},
			{
				id: 13,
				label: 'Turkish',
				language: 'tur',
				kind: 'subtitles',
				file: '/Spring.(2019)/subtitles/Spring.(2019).NoMercy.tur.full.vtt',
			},
			{
				id: 14,
				file: '/Spring.(2019)/thumbs_320x132.vtt',
				kind: 'thumbnails',
			},
			{
				id: 15,
				file: '/Spring.(2019)/thumbs_320x132.webp',
				kind: 'sprite',
			},
		],
	},
	{
		id: 'the-daily-dweebs',
		title: 'The Daily Dweebs',
		description: 'A pilot episode of an animated series revolving around the pet Dixey and his shenanigans in 1950\'s American suburbia.',
		image: '/8oCW8Njdabb9K3OwK1y8KUsHFvk.jpg',
		file: '/The.Daily.Dweebs.(2017)/The.Daily.Dweebs.(2017).NoMercy.m3u8',
		duration: '1:00',
		episode: 15,
		year: 2017,
		tracks: [
			{
				id: 0,
				file: '/The.Daily.Dweebs.(2017)/thumbs_320x180.vtt',
				kind: 'thumbnails',
			},
			{
				id: 1,
				file: '/The.Daily.Dweebs.(2017)/thumbs_320x180.webp',
				kind: 'sprite',
			},
		],
	},
	{
		id: 'wing-it',
		title: 'Wing It!',
		description: 'An uptight engineer gets an unwelcome visit from an enthusiastic wannabe-pilot, causing both of them to be launched into the air inside an out-of-control space shuttle.',
		image: '/o2G1kW9pCcRo7NmiZhJBm5LcVpH.jpg',
		file: '/Wing.It.(2023)/Wing.It.(2023).NoMercy.m3u8',
		duration: '3:58',
		episode: 16,
		year: 2023,
		tracks: [
			{
				id: 0,
				file: '/Wing.It.(2023)/thumbs_320x178.vtt',
				kind: 'thumbnails',
			},
			{
				id: 1,
				file: '/Wing.It.(2023)/thumbs_320x178.webp',
				kind: 'sprite',
			},
		],
	},
	{
		id: 'bipbop',
		title: 'BipBop',
		description: 'BipBop is a video test media file from Apple. It is used to test HLS streaming and player functionality. The media file is a 30-minute video of a person talking and includes a subtitle track in English. The video is encoded in H.264 and the audio is encoded in AAC. The subtitle track is encoded in WebVTT format',
		image: 'https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/poster.png',
		file: 'https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8',
		duration: '30:00',
		episode: 17,
		tracks: [
			{
				id: 0,
				label: 'English (Full)',
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/Examples/refs/heads/master/public/example_subtitle.vtt',
				language: 'eng',
				kind: 'subtitles',
			},
		],
	},
	{
		id: 'rail-wars',
		title: 'Rail Wars',
		description: 'Takayama enters the training program of JNR with the ambition of becoming one of the venerable train company\'s engineers. As a trainee he is teamed up with fight-ready Sakurai and stolid Iwaizumi and fellow Haruka Kōmi who has encyclopedic knowledge of trains. Together they learn how security officers for the train line work and get involved in more than one tricky situation.',
		image: 'https://image.tmdb.org/t/p/original/vH8NqN2LMcmtBv037iHGwcPOgCZ.jpg',
		file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/refs/heads/master/Anime/Anime/Rail.Wars!.(2014)/Rail.Wars!.S00E00/Rail.Wars!.(2014).S00E00.NoMercy.m3u8',
		duration: '1:30',
		episode: 18,
		tracks: [
			{
				id: 0,
				label: 'English (Full)',
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/refs/heads/master/Anime/Anime/Rail.Wars!.(2014)/Rail.Wars!.S00E00/subtitles/Rail.Wars!.(2014).S00E00.NoMercy.eng.full.ass',
				language: 'eng',
				kind: 'subtitles',
			},
			{
				id: 1,
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/refs/heads/master/Anime/Anime/Rail.Wars!.(2014)/Rail.Wars!.S00E00/fonts.json',
				kind: 'fonts',
			},
		],
	},
	{
		id: 'no-rin',
		title: 'No-Rin',
		description: 'The sudden retirement of the famous idol Yuka Kusakabe from the entertainment business shocks the world and devastates her biggest fan, teenager Kosaku Hata. His classmates at the Tamo Agriculture School manages to get him out of his depression and bring him out of his room to attend his classes. But to everyone\'s surprise, Yuka Kusakabe - her stage name - comes into their class under the name Ringo Kinoshita as a transfer student. Kosaku realizes he has a once-in-a-lifetime opportunity to get to personally know his dream girl and, together with his group of friends, try to find out why she came to the agricultural school and become more than just classmates.',
		image: 'https://image.tmdb.org/t/p/original/myHS6X2yonpoBQOptVuQ85PudtC.jpg',
		file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/refs/heads/master/Anime/Anime/No-Rin.(2014)/No-Rin.S00E00/No-Rin.(2014).S00E00.NoMercy.m3u8',
		duration: '23:39',
		episode: 19,
		tracks: [
			{
				id: 0,
				label: 'English (Full)',
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/refs/heads/master/Anime/Anime/No-Rin.(2014)/No-Rin.S00E00/subtitles/No-Rin.(2014).S00E00.NoMercy.eng.full.ass',
				language: 'eng',
				kind: 'subtitles',
			},
			{
				id: 1,
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/refs/heads/master/Anime/Anime/No-Rin.(2014)/No-Rin.S00E00/fonts.json',
				kind: 'fonts',
			},
		],
	},
];

export default playlist;